car_prices_tool_website/api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # CRUD
    path('cars/results', views.CarsResults.as_view(), name='api_results'),
    path('cars/create', views.CarCreate.as_view(), name='api_create'),
    path('cars/<int:pk>', views.CarRetrieveUpdateDestroy.as_view(), name='api_details'),

    # Auth
    path('signupuser', views.sign_up_user, name='api_signupuser'),
    path('gettoken', views.get_token, name='api_gettoken')
]

car_prices_tool_website/car_prices_tool_django/urls.py
import api
from api import urls
from django.contrib import admin
from django.contrib.auth import views as django_auth_views
from django.urls import path, include
from car_prices_tool.views import auth_views, price_tools_views, templates_views, users_views


urlpatterns = [
    # Admin:
    path('admin/', admin.site.urls, name='admin'),

    # Templates:
    path('', templates_views.home, name='home'),
    path('about/', templates_views.about, name='about'),
    path('features/', templates_views.features, name='features'),
    path('pricing/', templates_views.pricing, name='pricing'),
    path('search/', price_tools_views.search, name='search'),
    path('results/', price_tools_views.results, name='results'),
    path('results_demo/', price_tools_views.results_demo, name='results_demo'),
    path('no_results/', price_tools_views.no_results, name='no_results'),
    path('go_premium/', users_views.go_premium, name='go_premium'),
    path('go_api_pro/', users_views.go_api_pro, name='go_api_pro'),
    path('api_documentation/', templates_views.api_documentation, name='api_documentation'),

    # Authorization:
    path('signup/', auth_views.SignUpView.as_view(), name='signup'),
    path('login/', django_auth_views.LoginView.as_view(), name='login'),
    path('logout/', django_auth_views.LogoutView.as_view(), name='logout'),

    # API:
    path('api/', include(api.urls)),

    # Ajax:
    path('ajax/load_models/', templates_views.load_models, name='ajax_load_models'),

    # Django Debug Toolbar
    # path(r'^__debug__', include(debug_toolbar.urls))
]

car_prices_tool_website/car_prices_tool/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import JSONField


class Car(models.Model):
    make = models.CharField(max_length=50)
    model = models.CharField(max_length=50, null=True)
    model_variant = models.CharField(max_length=100, null=True)
    production_year = models.IntegerField(null=True)
    engine_power = models.IntegerField(null=True)
    mileage = models.IntegerField(null=True)
    engine_capacity = models.FloatField(null=True)
    offer_type = models.CharField(max_length=10, null=True)
    price = models.IntegerField()
    price_currency = models.CharField(max_length=10, null=True)
    state = models.CharField(max_length=10, null=True)
    price_dollars = models.IntegerField(null=True)
    date_scraped = models.DateField(null=True)
    date_issued = models.DateField(null=True)

    def __str__(self):
        return self.make


class UserSearchQuery(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    search_parameters = JSONField()


class UserPremiumRank(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rank = models.CharField(max_length=50)

    def __str__(self):
        return self.rank

car_prices_tool_website/car_prices_tool/views.py
import pendulum
from datetime import date

from django import template
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.db.models import Count, Avg
from django.shortcuts import render, redirect
from rest_framework.authtoken.models import Token

from car_prices_tool import all_jscharts
from car_prices_tool.forms import SearchCarForm, FreeSearchCarForm
from car_prices_tool.models import Car, UserSearchQuery, UserPremiumRank

register = template.Library()

# Current rates of conversion.
usd_pln = 3.73
usd_eur = 0.82


# Home is also a landing page.
def home(request):
    form = FreeSearchCarForm

    if request.method == 'POST':
        filled_form = FreeSearchCarForm(request.POST)
        if filled_form.is_valid():
            context = {
                'make': filled_form.cleaned_data['make'],
                'state': filled_form.cleaned_data['state'],
                'model': filled_form.cleaned_data['model'],
            }

            return results_demo(request, context)
        else:
            context = {
                'form': filled_form,
            }

            return render(request, 'car_prices_tool/home.html', context)
    else:
        context = {
            'form': form,
            'home_popularmakes_barchart': all_jscharts.home_popularmakes_barchart(),
            'home_popularproductionyears_piechart': all_jscharts.home_popularproductionyears_piechart(),
            'home_average_cars_used_info_radarchart': all_jscharts.home_average_cars_used_info_radarchart()
        }

        return render(request, 'car_prices_tool/home.html', context)


def about(request):
    return render(request, 'car_prices_tool/about.html')


def features(request):
    context = {
        'home_popularmakes_barchart': all_jscharts.home_popularmakes_barchart(),
        'home_popularproductionyears_piechart': all_jscharts.home_popularproductionyears_piechart(),
        'home_average_cars_used_info_radarchart': all_jscharts.home_average_cars_used_info_radarchart()
    }

    return render(request, 'car_prices_tool/features.html', context)


def pricing(request):
    return render(request, 'car_prices_tool/pricing.html')


@login_required(login_url='login')
def api_documentation(request):
    return render(request, 'car_prices_tool/api_documentation.html')


# This view is called when user search did not return any matches.
@login_required(login_url='login')
def no_results(request):
    return render(request, 'car_prices_tool/no_results.html')


@login_required(login_url='login')
def go_premium(request):
    if request.method == 'GET':
        try:
            user_rank_name = UserPremiumRank.objects.filter(user=request.user).values('rank').get()
        except UserPremiumRank.DoesNotExist:
            user_rank_name = {}

        if user_rank_name.get('rank') == 'Premium':
            context = {
                'message': 'You already have Premium account. Thank you!'
            }

            return render(request, 'car_prices_tool/go_premium.html', context)
        else:
            return render(request, 'car_prices_tool/go_premium.html')
    else:
        get_premium = UserPremiumRank(user=request.user, rank='Premium')
        get_premium.save()

        context = {
            'message': 'Thank you very much for supporting our website! Enjoy your premium account!'
        }

        return render(request, 'car_prices_tool/go_premium.html', context)


@login_required(login_url='login')
def go_api_pro(request):
    if request.method == 'GET':
        try:
            user_rank_name = UserPremiumRank.objects.filter(user=request.user).values('rank').get()
        except UserPremiumRank.DoesNotExist:
            user_rank_name = {}

        if user_rank_name.get('rank') == 'APIPRO':
            token = Token.objects.get(user=request.user)

            context = {
                'message': 'You already have API Pro account. Thank you!',
                'token': str(token)
            }

            return render(request, 'car_prices_tool/go_api_pro.html', context)
        else:
            return render(request, 'car_prices_tool/go_api_pro.html')
    else:
        UserPremiumRank.objects.filter(user=request.user).all().delete()
        get_api_pro = UserPremiumRank(user=request.user, rank='APIPRO')
        get_api_pro.save()

        token = Token.objects.create(user=request.user)

        context = {
            'message': 'Thank you very much for supporting our website! Enjoy your API Pro account!',
            'token': str(token)
        }

        return render(request, 'car_prices_tool/go_api_pro.html', context)


def sign_up_user(request):
    if request.method == 'GET':
        context = {
            'form': UserCreationForm()
        }

        return render(request, 'car_prices_tool/signup.html', context)
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(username=request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request, user)

                return redirect('search')
            except IntegrityError:
                context = {
                    'form': UserCreationForm(),
                    'error': 'This username is already taken. Please choose another one.'
                }

                return render(request, 'car_prices_tool/signup.html', context)
        else:
            context = {
                'form': UserCreationForm(),
                'error': 'Password did not match!'
            }

            return render(request, 'car_prices_tool/signup.html', context)


def log_in_user(request):
    if request.method == 'GET':
        context = {
            'form': AuthenticationForm()
        }

        return render(request, 'car_prices_tool/login.html', context)
    else:
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user:
            login(request, user)

            return redirect('search')
        else:
            context = {
                'form': AuthenticationForm(),
                'error': 'Wrong password or username.'
            }

            return render(request, 'car_prices_tool/login.html', context)


def log_out_user(request):
    if request.method == 'POST':
        logout(request)

        return render(request, 'car_prices_tool/home.html')


@login_required(login_url='login')
def search(request):
    cars = Car.objects.all()
    makes = Car.objects.values('make').annotate(entries=Count('make'))
    models = Car.objects.values('model').annotate(entries=Count('model'))

    form = SearchCarForm

    free_searches = 10
    premium_searches = 100
    apipro_searches = 500

    try:
        user_rank = UserPremiumRank.objects.filter(user=request.user).values('rank').get()
    except UserPremiumRank.DoesNotExist:
        user_rank = {}

    today = date.today()
    last_user_searches = UserSearchQuery.objects.filter(user=request.user, date__year=today.year, date__month=today.month, date__day=today.day).count()

    # Check how many searches user can make based on rank.
    if user_rank.get('rank') == 'Premium':
        available_searches = premium_searches - last_user_searches
    elif user_rank.get('rank') == 'APIPRO':
        available_searches = apipro_searches - last_user_searches
    else:
        available_searches = free_searches - last_user_searches

    # Additional value for frontend.
    searches_multiplied = last_user_searches * 10

    if request.method == 'POST':
        filled_form = SearchCarForm(request.POST)
        if filled_form.is_valid():
            context = {
                'make': filled_form.cleaned_data['make'],
                'state': filled_form.cleaned_data['state'],
                'model': filled_form.cleaned_data['model'],
                'offer_type': filled_form.cleaned_data['offer_type'],
                'mileage_less_more': filled_form.cleaned_data['mileage_less_more'],
                'mileage': filled_form.cleaned_data['mileage'],
                'production_year_less_more': filled_form.cleaned_data['production_year_less_more'],
                'production_year': filled_form.cleaned_data['production_year'],
                'price_less_more': filled_form.cleaned_data['price_less_more'],
                'price': filled_form.cleaned_data['price'],
                'price_currency': filled_form.cleaned_data['price_currency'],
                'engine_capacity_less_more': filled_form.cleaned_data['engine_capacity_less_more'],
                'engine_capacity': filled_form.cleaned_data['engine_capacity'],
                'engine_power_less_more': filled_form.cleaned_data['engine_power_less_more'],
                'engine_power': filled_form.cleaned_data['engine_power']
            }
            if user_rank.get('rank') == 'Premium':
                if last_user_searches < premium_searches:
                    new_search = UserSearchQuery(user=request.user, search_parameters=context)
                    new_search.save()

                    return results(request, context)
                else:
                    context = {
                        'quota_error': 'No searches left for today! Maybe go API Pro?'
                    }

                    return render(request, 'car_prices_tool/search.html', context)
            elif user_rank.get('rank') == 'APIPRO':
                if last_user_searches < apipro_searches:
                    new_search = UserSearchQuery(user=request.user, search_parameters=context)
                    new_search.save()

                    return results(request, context)
                else:
                    context = {

car_prices_tool_website/car_prices_tool/views/auth_views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('home')
    template_name = 'registration/signup.html'

    def form_valid(self, form):
        view = super(SignUpView, self).form_valid(form)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        login(self.request, user)

        return view

    def form_invalid(self, form):
        if User.objects.filter(username=self.request.POST['username']):
            context = {
                'form': UserCreationForm(),
                'error': 'This username is already taken.'
            }
        elif self.request.POST['password1'] != self.request.POST['password2']:
            context = {
                'form': UserCreationForm(),
                'error': 'Passwords do not match.'
            }
        else:
            context = {
                'form': UserCreationForm(),
                'error': 'Please make sure that your password have at least 8 characters and '
                         'that it is not too easy or too common. Your password also cannot be '
                         'entirely numeric and can not be too similar to your username.'
            }

        return render(self.request, 'registration/signup.html', context)

car_prices_tool_website/car_prices_tool/views/templates_views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.shortcuts import render

from car_prices_tool import all_jscharts
from car_prices_tool.forms import FreeSearchCarForm
from car_prices_tool.models import Car
from car_prices_tool.views.price_tools_views import results_demo


# Home is also a landing page.
def home(request):
    form = FreeSearchCarForm

    if request.method == 'POST':
        filled_form = FreeSearchCarForm(request.POST)
        if filled_form.is_valid():
            context = {
                'make': filled_form.cleaned_data['make'],
                'state': filled_form.cleaned_data['state'],
                'model': filled_form.cleaned_data['model'],
            }

            return results_demo(request, context)
        else:
            context = {
                'form': filled_form,
            }

            return render(request, 'car_prices_tool/home.html', context)
    else:
        context = {
            'form': form,
            'home_popularmakes_barchart': all_jscharts.home_popularmakes_barchart(),
            'home_popularproductionyears_piechart': all_jscharts.home_popularproductionyears_piechart(),
            'home_average_cars_used_info_radarchart': all_jscharts.home_average_cars_used_info_radarchart()
        }

        return render(request, 'car_prices_tool/home.html', context)


def about(request):
    return render(request, 'car_prices_tool/about.html')


def features(request):
    context = {
        'home_popularmakes_barchart': all_jscharts.home_popularmakes_barchart(),
        'home_popularproductionyears_piechart': all_jscharts.home_popularproductionyears_piechart(),
        'home_average_cars_used_info_radarchart': all_jscharts.home_average_cars_used_info_radarchart()
    }

    return render(request, 'car_prices_tool/features.html', context)


def pricing(request):
    return render(request, 'car_prices_tool/pricing.html')


@login_required(login_url='login')
def api_documentation(request):
    return render(request, 'car_prices_tool/api_documentation.html')


# This view is for AJAX call.
def load_models(request):
    make = request.GET.get('make')
    models = Car.objects.filter(make=make).values('model').annotate(count=Count('make')).order_by('count').distinct().reverse()
    models_count = []
    for model in models:
        models_count.append(Car.objects.filter(model=model['model']).count())

    data = zip(models, models_count)

    return render(request, 'car_prices_tool/models_dropdown_list_options.html', {'data': data})

car_prices_tool_website/car_prices_tool/templates/car_prices_tool/about.html
{% extends 'car_prices_tool/base.html' %}
{% load static %}

{% block content %}

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>About</title>
    </head>
    <body>

    <div class="d-flex justify-content-center">
        <div class="jumbotron jumbotron-fluid vertical-center">
            <div class="container">
                <h1 class="display-4">About</h1>
                <p class="lead">
                    Hello! On this mockup SaaS website without registering you can search my database by make and model
                    of the car.
                    After you create an account and you will log in you can select various filters like price, year of
                    production, mileage and many more. Since you created account you can use all available filters (that
                    non registered users cannot) you can make 10 searches per 24 hours. But if you click button "Go
                    Premium" you will be granted new "Premium" rank that will let you make 100 searches per 24 hours.
                    It is a mockup SaaS after all. You can also go "API Pro" to receive access to searching through API
                    and up to 500 searches per day.
                    <br><br>
                    I created this website in order to train my programming skills. In development I used
                    Django, Django REST API, Python, HTML, CSS, BootStrap and a little bit of JavaScript (thanks
                    <a href="https://www.chartjs.org/" target="_blank">Chart.js</a>) and Ajax. In order to gain data
                    for cars database I used web scraping with Scrapy and Docker for hosting my spider on VPS server.
                    <br><br>
                    If you would like you can check my other projects on GitHub
                    <a href="https://github.com/m-niemiec?tab=repositories" target="_blank">here</a>.
                    <br><br>
                    If you would like to read more about this project (or my other projects) please visit my
                    <a href="https://www.michalniemiec.info/" target="_blank">portfolio</a>.
                    <br><br>
                    If you would like to contact me, you can write at <b>michal.niemiec.it *at* gmail.com</b>
                    <br><br>
                    Thanks and Cheers, Michał!
                </p>
            </div>
        </div>
    </div>

    </body>
    </html>

{% endblock %}

car_prices_tool_website/car_prices_tool/templates/car_prices_tool/api_documentation.html
{% extends 'car_prices_tool/base.html' %}
{% load static %}

{% block content %}

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>About</title>
    </head>
    <body>

    <div class="jumbotron jumbotron-fluid vertical-center">
        <div class="container">
            <h1 class="display-4">API Documentation:</h1>
            <p class="lead">
                Here are two ways that you can access our API.<br><br>
                Through CURL Request:<br>
                <code>
                    curl -X "GET" https://carpricestool.eu.pythonanywhere.com/api/cars/results<br>
                    -H "Content-Type: application/json"<br>
                    -H "Authorization: Token YOURTOKEN"<br>
                    -d 'filter1=value1'<br>
                    -d 'filter2=value2'<br>
                    -d 'filter3=value3'
                </code>
                <br><br>
                Through URL Request:<br>
                <code>
                    https://carpricestool.eu.pythonanywhere.com/api/cars/results?auth_token=YOURTOKEN&filter1=value1&filter2=value2&filter3=value3
                </code>
                <br><br>
                Following filters are available:<br>

            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Filter</th>
                    <th scope="col">Values or Examples</th>
                    <th scope="col">Requirements</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>make</td>
                    <td>eq. 'Kia'</td>
                    <td></td>
                </tr>
                <tr>
                    <td>state</td>
                    <td>Used, New (if you don't provide this filter, both will be returned)</td>
                    <td></td>
                </tr>
                <tr>
                    <td>model</td>
                    <td>eq. 'Ceed'</td>
                    <td></td>
                </tr>
                <tr>
                    <td>offer_type</td>
                    <td>business, person</td>
                    <td></td>
                </tr>
                <tr>
                    <td>mileage_less_more</td>
                    <td>mileage_less_than, mileage_more_than</td>
                    <td>Needs mileage</td>
                </tr>
                <tr>
                    <td>mileage</td>
                    <td>eq. '125000'</td>
                    <td>Needs mileage_less_more</td>
                </tr>
                <tr>
                    <td>production_year_less_more</td>
                    <td>production_year_less_than, production_year_more_than, production_year_exact</td>
                    <td>Needs production_year</td>
                </tr>
                <tr>
                    <td>production_year</td>
                    <td>eq. '2018'</td>
                    <td>Needs production_year_less_more</td>
                </tr>
                <tr>
                    <td>price_less_more</td>
                    <td>price_less_than, price_more_than</td>
                    <td>Needs price and price_currency</td>
                </tr>
                <tr>
                    <td>price</td>
                    <td>eq. '12000'</td>
                    <td>Needs price_less_more and price_currency</td>
                </tr>
                <tr>
                    <td>price_currency</td>
                    <td>USD, PLN, EUR</td>
                    <td>Needs price_less_more and price</td>
                </tr>
                <tr>
                    <td>engine_capacity_less_more</td>
                    <td>engine_capacity_less_than, engine_capacity_more_than, engine_capacity_equal</td>
                    <td>Needs engine_capacity</td>
                </tr>
                <tr>
                    <td>engine_capacity</td>
                    <td>eq. '1.8'</td>
                    <td>Needs engine_capacity_less_more</td>
                </tr>
                <tr>
                    <td>engine_power_less_more</td>
                    <td>engine_power_less_than, engine_power_more_than, engine_power_equal</td>
                    <td>Needs engine_power</td>
                </tr>
                <tr>
                    <td>engine_power</td>
                    <td>eq. '90'</td>
                    <td>Needs engine_power_less_more</td>
                </tr>
                </tbody>
            </table>
            <br><br>
            Please note that API will return only first 500 cars. If your search is hitting this limit, please narrow it.
            </p>
        </div>
    </div>

    </body>
    </html>

{% endblock %}

car_prices_tool_website/car_prices_tool/templates/car_prices_tool/go_api_pro.html
{% extends 'car_prices_tool/base.html' %}
{% load static %}

{% block content %}

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>About</title>
    </head>
    <body>

    <div class="jumbotron jumbotron-fluid vertical-center">
        <div class="container">
            {% if message %}
                <h1 class="display-4">
                    <div class="alert alert-success" role="alert">
                        {{ message }}
                    </div>
                </h1>
                <br><br>
            {% endif %}
            {% if user_rank_name == 'Free' or user_rank_name == 'Premium' %}
                <p class="lead">
                    Hello! If you would like to purchase API Pro status for your account and receive your own API
                    Key / Token please click here:
                </p>
                <form action="{% url 'go_api_pro' %}" method="post">
                    {% csrf_token %}
                    <div style="text-align: center;">
                        <button type="submit" class="btn btn-primary btn-lg">GO API Pro!</button>
                    </div>
                </form>
            {% else %}
                <div style="text-align: center;">
                    <p class="lead">
                        Here is your own API Key / Token:<br>
                    </p>
                    {{ token }}
                    <br><br>
                    <a href="{% url 'api_documentation' %}">Read API Documentation</a>
                </div>
            {% endif %}
        </div>
    </div>

    </body>
    </html>

{% endblock %}

car_prices_tool_website/car_prices_tool/templates/car_prices_tool/home.html
{% extends 'car_prices_tool/base.html' %}
{% load static %}

{% block content %}

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Car Prices Tool</title>
    </head>
    <body>
    <div class="jumbotron jumbotron-fluid vertical-center">
        <div class="container">
            <h1 class="display-4">Welcome on Car Prices Tool website!</h1>
            <p class="lead">
                Hi! Aren't you tired with searching for prices and comparisons of cars that you are interest in?
                Looking for best price/mileage/production year proportions?
                <br><br>
                All that tedious research and wondering how much cheaper it would be to select car that is 5
                years older but mileage is better?
                <br><br>
                Well. No more! With our tool you will be able to check all those information in just few clicks.
                Check out our <b>small</b> demo here and please tell us ...
            </p>
            <br><br>
            <div class="form-group">
                <form method="post" id="SearchForm" data-models-url="{% url 'ajax_load_models' %}" novalidate>
                    {% csrf_token %}
                    <h1 class="display-4">What car are you looking for?</h1>

                    {% if quota_error %}
                        <div class="alert alert-danger" role="alert">
                            {{ quota_error }}
                        </div>
                    {% endif %}

                    <div class="row">
                        <div class="col-sm">
                            {{ form.make }}
                            {{ form.make.errors }}
                        </div>
                        <div class="col-sm">
                            {{ form.model }}
                            {{ form.model.errors }}
                        </div>
                        <div class="col-sm">
                            <ul id="parent">

                                {% for choice in form.state %}
                                    <li>
                                        {{ choice }}
                                        {{ choice.errors }}
                                    </li>
                                {% endfor %}

                            </ul>
                            <br>
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-10">
                                <button type="submit" class="btn btn-success btn-lg">Search!</button>&nbsp;&nbsp;&nbsp;
                                <button type="reset" class="btn btn-danger btn-lg">Start over</button>
                            </div>
                        </div>
                    </div>
                </form>
                {#Ajax call for loading up models based on selected make.#}
                <script>
                    $("#id_make").change(function () {
                        const url = $("#SearchForm").attr("data-models-url");
                        const makeId = $(this).val();

                        $.ajax({
                            url: url,
                            data: {
                                'make': makeId
                            },
                            success: function (data) {
                                $("#id_model").html(data);
                            }
                        });

                    });
                </script>
            </div>
            <br><br>
            {% if not user.is_authenticated %}
                <div class="alert alert-info" role="alert">
                    To see <b>additional filters</b> please
                        <a href="{% url 'signup' %}" class="alert-link">Create Free Account Here!</a>
                </div>
                    {% else %}
                <div class="alert alert-success" role="alert">
                    Use <b>full</b> version with many additional filters
                        <a href="{% url 'search' %}" class="alert-link">here!</a>
                </div>
            {% endif %}
        </div>
    </div>
    </body>
    </html>

{% endblock %}

car_prices_tool_website/car_prices_tool/templates/car_prices_tool/models_dropdown_list_options.html
<option value="">--- choose model ---</option>
{% for model, count in data %}
    <option value="{{ model.model }}">{{ model.model }} ({{ count }})</option>
{% endfor %}